apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: gcr.io/ece9016-417921/nginx:latest
          ports:
            - containerPort: 80
        - name: one-page-db
          image: gcr.io/ece9016-417921/one-page-db:latest
          env:
            - name: DATABASE_URL
              value: postgres://myuser:secret@database-service:5432/mydatabase
          ports:
            - containerPort: 8080
