apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: DB
  template:
    metadata:
      labels:
        app: DB
    spec:
      containers:
        - image: postgres
          name: postgres-container
          ports:
            - containerPort: 5432
          imagePullPolicy: Always
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: user
            - name: PGDATA
              value: /mnt/postgres/pgdata
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /mnt/postgres
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
